---
title: "Extra IPL"
author: "Arlton Gilbert"
date: "25/10/2021"
output: html_document
---

```{r setup, include=FALSE}
#FILENUM: 1
knitr::opts_chunk$set(echo = TRUE)
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
library(tidyverse)
library("xlsx")
library(readxl)
library(rvest) #used for webscraping 
rm(list=ls())
start.time <- Sys.time()
#Average Run Time ~ 1.2min
```

```{r data}
new_scorecards = read_xlsx(path = "Data/IPL_SCHEDULE_2008_2021.xlsx",sheet ="2021")
new_scorecards %>% rename(Match_Cricbuzz_URL = Scorecard)
new_scorecards$Match_Result = 0
new_scorecards$Match_Date = 0
new_scorecards$Stadium = 0
new_scorecards$Location = 0
new_scorecards$Match_Team = 0
count = 0

for (new_match in new_scorecards$Scorecard){
  count = count + 1
  matchi = read_html(new_match)
  matchi %>% html_nodes('.cb-text-complete')
  new_scorecards$Match_Result[count] = matchi %>% html_nodes('.cb-text-complete') %>% html_text()
  new_scorecards$Match_Result[count] = matchi %>% html_nodes('.cb-text-complete') %>% html_text()  
  stadiums = matchi %>% html_nodes('.text-gray span')
  new_scorecards$Match_Date[count] = paste0((matchi %>% html_nodes('.pad-left+ span span , .pad-left~ .pad-left'))[2] %>% html_text(),"2021")  
  new_scorecards$Stadium[count] = gsub(",","",str_trim(stadiums[1] %>% html_text())) #paste0(stadiums[1] %>% html_text(),stadiums[2] %>% html_text())  
  new_scorecards$Location[count] = stadiums[2] %>% html_text()   
  new_scorecards$Match_Team[count] = strsplit(matchi %>% html_nodes('.line-ht24') %>% html_text(),",")[[1]][1]   
}

head(new_scorecards)

```

```{r replacements}
new_scorecards_edited = new_scorecards
new_scorecards_edited$Match_Team = gsub('VS','vs',toupper(gsub('Punjab', 'Kings XI Punjab', gsub('Kolkata','Kolkata Knight Riders',gsub('Delhi','Delhi Capitals',gsub('Rajasthan','Rajasthan Royals',gsub('Hyderabad','Sunrisers Hyderabad', gsub('Chennai','Chennai Super Kings', gsub('Bangalore', 'Royal Challengers Bangalore', gsub('Mumbai','Mumbai Indians', new_scorecards$Match_Team))))))))))

```

```{r write}
write.xlsx(new_scorecards_edited, file = "Data/IPL_SCHEDULE_2008_2021 Extension.xlsx",sheetName = '2021 Updated', append = FALSE)

```


```{r savestate}
end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken

#Savestate so we don't have to rerun computationally intensive parts later
save.image(file='WebScraper 2021.RData')

```

```{r loadstate}
#Savestate so we don't have to rerun computationally intensive parts later
#load(file='WebScraper 2021.RData')

```

```{r runabove}
```
